### ISSUE TITLE
Matches Page

### ISSUE THREAD

**Issue by josephpanossian** [josephpanossian/dota-viz#1]

**Comment by josephpanossian** [comment]
# Feature Overview
Add a page that displays a players match history. Match history should be sortable, filterable, searchable. List items should be interactable to display preview of match details, with navigation option to full match details page.

## Tasks

- [ ] Display List of Player Matches
- [ ] Sort matches by table headers
- [ ] Filter matches by Heroes/Win/Lose/...
- [ ] Search matches by ID
- [ ] Match Preview Modal
